# Generated by Django 4.2.3 on 2023-08-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jual_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30, unique=True)),
                ('alamat', models.TextField()),
                ('contact', models.TextField()),
                ('gmaps', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30, unique=True)),
                ('jabatan', models.CharField(max_length=30)),
                ('alamat', models.TextField()),
                ('deskripsi', models.TextField()),
                ('foto', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AIcamModel',
        ),
        migrations.DeleteModel(
            name='AIchatModel',
        ),
        migrations.DeleteModel(
            name='DetailsModel',
        ),
        migrations.DeleteModel(
            name='Donasi',
        ),
        migrations.DeleteModel(
            name='Jual',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
