# Generated by Django 4.2.3 on 2023-08-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dpd_dpp_delete_aicammodel_delete_aichatmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpd',
            name='email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
